# Generated by Django 6.0.2 on 2026-03-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myportfolio', '0004_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/'),
        ),
    ]
